import { Device, Partition } from './types';

export const SAMSUNG_DEVICES: Device[] = [
  {
    id: 'herolte',
    modelName: 'Galaxy S7',
    modelNumber: 'SM-G930F',
    soc: 'Exynos 8890',
    architecture: 'ARM64',
    pitSize: 4,
    usbType: 'Micro-USB',
    downloadCombo: 'Hold [Vol Down] + [Home] + [Power], then press [Vol Up]',
    jigSupported: true,
    hasBixby: false,
    hasHomeButton: true,
  },
  {
    id: 'dreamlte',
    modelName: 'Galaxy S8',
    modelNumber: 'SM-G950F',
    soc: 'Exynos 8895',
    architecture: 'ARM64',
    pitSize: 4,
    usbType: 'USB-C',
    downloadCombo: 'Hold [Vol Down] + [Bixby] + [Power], then press [Vol Up]',
    jigSupported: true,
    hasBixby: true,
    hasHomeButton: false,
  },
  {
    id: 'beyond1lte',
    modelName: 'Galaxy S10',
    modelNumber: 'SM-G973F',
    soc: 'Exynos 9820',
    architecture: 'ARM64',
    pitSize: 4,
    usbType: 'USB-C',
    downloadCombo: 'Power off, hold [Vol Down] + [Bixby] and plug in USB cable',
    jigSupported: true,
    hasBixby: true,
    hasHomeButton: false,
  },
  {
    id: 'klte',
    modelName: 'Galaxy S5',
    modelNumber: 'SM-G900F',
    soc: 'Snapdragon 801',
    architecture: 'ARM',
    pitSize: 4,
    usbType: 'Micro-USB',
    downloadCombo: 'Hold [Vol Down] + [Home] + [Power], then press [Vol Up]',
    jigSupported: true,
    hasBixby: false,
    hasHomeButton: true,
  },
  {
    id: 'i9300',
    modelName: 'Galaxy S III',
    modelNumber: 'GT-I9300',
    soc: 'Exynos 4412',
    architecture: 'ARM',
    pitSize: 4,
    usbType: 'Micro-USB',
    downloadCombo: 'Hold [Vol Down] + [Home] + [Power], then press [Vol Up]',
    jigSupported: true,
    hasBixby: false,
    hasHomeButton: true,
  },
  {
    id: 'a52sxq',
    modelName: 'Galaxy A52s 5G',
    modelNumber: 'SM-A528B',
    soc: 'Snapdragon 778G',
    architecture: 'ARM64',
    pitSize: 8,
    usbType: 'USB-C',
    downloadCombo: 'Power off, hold [Vol Up] + [Vol Down] and plug in USB cable',
    jigSupported: false,
    hasBixby: false,
    hasHomeButton: false,
  },
];

export const DEFAULT_PARTITIONS: Partition[] = [
  { name: 'BOOT', flashFilename: 'boot.img', size: '32 MB', description: 'Kernel and RAMDisk', color: 'bg-emerald-800' },
  { name: 'RECOVERY', flashFilename: 'recovery.img', size: '48 MB', description: 'TWRP / Custom Recovery', color: 'bg-amber-800' },
  { name: 'SYSTEM', flashFilename: 'system.img', size: '3.5 GB', description: 'Android OS / LineageOS', color: 'bg-blue-800' },
  { name: 'VENDOR', flashFilename: 'vendor.img', size: '512 MB', description: 'Hardware Drivers & HAL', color: 'bg-indigo-800' },
  { name: 'USERDATA', flashFilename: 'userdata.img', size: 'Varies', description: 'User Apps & Encrypted Storage', color: 'bg-zinc-700' },
  { name: 'CACHE', flashFilename: 'cache.img', size: '256 MB', description: 'System Cache & Dalvik', color: 'bg-slate-700' },
  { name: 'RADIO', flashFilename: 'modem.bin', size: '64 MB', description: 'Baseband / Cellular Modem', color: 'bg-purple-800' },
];
